name: moduled_intl_utils
description: moduled_intl_utils is a dart library that generates Dart localization code from ARB file for multiple modules. Generated code relies on Intl library. Forked from https://github.com/localizely/intl_utils
version: 2.7.0
homepage: https://github.com/localizely/moduled_intl_utils

environment:
  sdk: ">=2.19.6 <3.7.0"

dependencies:
  analyzer: ^5.12.0
  archive: ^3.3.7
  args: ^2.4.1
  dart_style: ^2.3.1
  http: ^0.13.6
  intl: ^0.18.1
  path: ^1.8.3
  petitparser: ^5.4.0
  yaml: ^3.1.2
  intl_utils: ^2.8.2

dev_dependencies:
  build_runner: ^2.4.2
  lints: ^2.1.0
  mockito: ^5.4.0
  test: ^1.24.2
